
[functions.seed-absence-types]
enabled = true
verify_jwt = true
import_map = "./functions/seed-absence-types/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/seed-absence-types/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/seed-absence-types/*.html" ]
